// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Strand struct {
	ID        string   `json:"id"`
	Name      string   `json:"name"`
	Theme     string   `json:"theme"`
	Spanogram string   `json:"spanogram"`
	Words     []string `json:"words"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
