version: '3.8'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: iyc
      MONGO_INITDB_ROOT_PASSWORD: iyc-nyt

volumes:
  db_data: